#!/bin/bash
time=$(date +%F)
cursectime=$(date -d"$time" +%s)
cursectime=$(( $cursectime - 604800 ))
echo "$time" > timefolder
ls /home/user | grep -E "Backup-" | cut -f 1 -d '-' --complement |
while read elem
do
backtime=$(date -d"$elem" +%s)
if [ "$cursectime" -le "$backtime" ]
then
echo "$elem" > timefolder
break
fi
done
read Line < timefolder
time="$Line"
rm timefolder
if ! [ -e "$HOME/Backup-$time" ]
then
mkdir $HOME/Backup-$time
cp $HOME/source/* $HOME/Backup-$time/
echo "New backup created Name : Backup-$time : Date : $time $(ls $HOME/Backup-$time)" > $HOME/backup-report
else
ls $HOME/source |
while read Info
do
if ! [ -z "$(find $HOME/Backup-$time -name "$Info.*")" ]
then
if [ "$(stat -c%s "$(find $HOME/Backup-$time -name "$Info.*")")" -ne "$(stat -c%s "$HOME/source/$Info")" ]
then
rm $(find $HOME/Backup-$time -name "$Info.*")
cp $HOME/source/$Info $HOME/Backup-$time/$Info.$(date +%F)
fi
else
if [ -e "$HOME/Backup-$time/$Info" ]
then
if [ "$(stat -c%s "$(find $HOME/Backup-$time -name "$Info")")" -ne "$(stat -c%s "$HOME/source/$Info")" ]
then
cp $HOME/source/$Info $HOME/Backup-$time/$Info.$(date +%F)
fi
else
cp $HOME/source/$Info $HOME/Backup-$time/$Info
fi
fi
done
fi
