#!/bin/bash
mkdir $HOME/test && echo "catalog test was created successfully" >> ~/report && > $HOME/test/$(date '+%d-%m-%Y_%H-%M-%S')
ping www.net_nikogo.ru || echo "$(date '+%d-%m-%Y_%H-%M-%S') WARNING" >> ~/report
