#!/bin/bash

if ! [ -d $HOME/restore/ ]
then
mkdir $HOME/restore/
fi

ls $HOME | grep "Backup-" | cut -f 1 -d '-' --complement | 
while read line; do
echo "$(date -d "$line" +%s)" >> upback_buffer.buffer
done

backdate=$(cat upback_buffer.buffer | sort -n | tail -n 1)
backdate=$(date -d @$backdate +%F)

rm upback_buffer.buffer

ls $HOME/Backup-$backdate |
while read line; do
if ! [ -z $(find $HOME/Backup-$backdate -name "$line.*") ]
then
continue
fi
if (( $(echo "$line" | awk -F"." '{print NF}') > 1 ))
then
if [[ $(echo "$line" | awk -F"." '{print $NF}') =~ ^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$ ]]
then
num=$(echo "$line" | awk -F"." '{print NF}')
newname=$(echo "$line" | cut -d. -f$num --complement)
cp $HOME/Backup-$backdate/$line $HOME/restore/$newname
else
cp $HOME/Backup-$backdate/$line $HOME/restore/
fi
else
cp $HOME/Backup-$backdate/$line $HOME/restore/
fi
done
